import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import localFont from "next/font/local";
import Header from "@/components/Header/Header";
import {
  Card,
  CardContent,
  CardImage,
  CardTitle,
} from "@/components/card/Card";
import { CardHeader } from "@chakra-ui/card";
import { Tag2, TagItem } from "@/components/Tag2/Tag2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: [
    {
      path: "../fonts/Pretendard/Pretendard-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Pretendard/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Pretendard/Pretendard-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Pretendard/Pretendard-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "fallback",
});

const Godo = localFont({
  src: [
    {
      path: "../fonts/Godo/GodoM.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/../fonts/Godo/GodoB.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-godo",
  display: "fallback",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${Godo.variable} ${pretendard.variable}`}>
        <Header />
        <div
          id={"blog_wrap"}
          className={"flex"}
          style={{ maxWidth: "1920px", margin: "0 auto" }}
        >
          <section
            className={"max-w-[1440px] pl-[60px] mr-[24px]"}
            style={{ width: "calc(100% - 460px)" }}
          >
            <h1
              className={
                "accent-title-color font-godoB text-5xl font-normal py-[60px]"
              }
            >
              개발 블로그
            </h1>
            <Providers>{children}</Providers>
          </section>
          <section
            className={"sticky w-[400px] gap-[20px] pr-[60px]"}
            style={{ boxShadow: "0px 8px 15px 0px rgba(0, 0, 0, 0.25)" }}
          >
            <div>
              <h2
                className={
                  "accent-title-color font-godoB text-2xl font-normal pl-[30px] py-[20px]"
                }
                style={{
                  borderBottom: "1px solid #DFE3E8",
                }}
              >
                실시간 인기글
              </h2>
              <div className={"flex flex-col pl-[30px] mt-[20px] gap-5"}>
                <Card>
                  <CardImage width={"104px"} height={"86px"} />
                  <CardContent>
                    <CardTitle
                      className={"font-pretendard"}
                      style={{ fontSize: "20px" }}
                    >
                      여기는 타이틀 영역입니다.
                    </CardTitle>
                  </CardContent>
                </Card>
                <Card>
                  <CardImage width={"104px"} height={"86px"} />
                  <CardContent>
                    <CardTitle
                      className={"font-pretendard"}
                      style={{ fontSize: "20px" }}
                    >
                      여기는 타이틀 영역입니다.
                    </CardTitle>
                  </CardContent>
                </Card>
                <Card>
                  <CardImage width={"104px"} height={"86px"} />
                  <CardContent>
                    <CardTitle
                      className={"font-pretendard"}
                      style={{ fontSize: "20px" }}
                    >
                      여기는 타이틀 영역입니다.
                    </CardTitle>
                  </CardContent>
                </Card>
              </div>
            </div>
            <div>
              <h2
                className={
                  "accent-title-color font-godoB text-2xl font-normal pl-[30px] py-[20px]"
                }
                style={{
                  borderBottom: "1px solid #DFE3E8",
                }}
              >
                # 태그
              </h2>
              <div className={"pl-[30px]"}>
                <Tag2>
                  <TagItem name={"Tag name"} />
                </Tag2>
              </div>
            </div>
          </section>
        </div>
      </body>
    </html>
  );
}
